
export type CategoryType = 'Mind' | 'Body' | 'Study' | 'Sleep' | 'Break' | 'Medicine';

export interface MainTask {
  name: string;
  targetDate: string; // ISO String
}

export interface Task {
  id: string;
  name: string;
  category: CategoryType;
  startTime: string; // ISO String
  durationMinutes: number;
  completed: boolean;
  isSpacedRepetition?: boolean;
  isQuick?: boolean; 
  isMedicine?: boolean; 
  repetitionStep?: number;
}

export interface UserStats {
  streak: number;
  xp: number;
  hydrationCount: number;
  lastHydrationUpdate: number;
  dailyCompletion: Record<string, number>; // "YYYY-MM-DD": percentage
  mainTask?: MainTask;
  dailyGoal?: { goal: string; date: string };
  focusSubjects?: { subject: string; endDate: string }[]; // NEW: Subject focus for next N days
}

export type PandaState = 'IDLE' | 'MEDITATING' | 'READING' | 'EXERCISING' | 'PLAYING' | 'SHOCKED' | 'HIDING' | 'SLEEPING';

export enum Tab {
  HOME = 'home',
  SCHEDULER = 'scheduler',
  SPACED = 'spaced',
  ANALYTICS = 'analytics',
  SETTINGS = 'settings',
  SENSEI = 'sensei',
  EXAM = 'exam'
}

export const CATEGORY_COLORS: Record<CategoryType, string> = {
  Mind: '#8B5FBF',
  Body: '#48BB78',
  Study: '#F6AD55',
  Sleep: '#4FD1C7',
  Break: '#CBD5E0',
  Medicine: '#EF4444'
};

export interface UserAccount {
  username: string;
  createdAt: string;
}

export interface UserVaultData {
  userName: string;
  userLocation: string;
  startDate: string;
  tasks: Task[];
  stats: UserStats;
  hydration: number;
  sleepConfig: { bedtime: string; duration: number };
  remindersEnabled: boolean;
  examPlans?: ExamPlan[];
}

// ── EXAM PLANNER TYPES ──────────────────────────────────────────────────

export interface SyllabusTopic {
  id: string;                // unique id e.g. Math.random().toString(36).substr(2,9)
  name: string;              // e.g. "Linear Algebra: Matrix Algebra"
  subject: string;           // parent subject e.g. "Engineering Mathematics"
  estimatedMinutes: number;  // computed by the auto-weight algorithm
  completed: boolean;        // user marks this done
}

export interface ExamPlan {
  id: string;
  examName: string;          // e.g. "GATE CE 2027"
  examDate: string;          // ISO date string "YYYY-MM-DD"
  createdAt: string;         // ISO date string
  dailyStudyMinutes: number; // how many minutes per day user wants to study (default 360 = 6h)
  revisionBufferDays: number;// final N days before exam reserved for revision (default 14)
  topics: SyllabusTopic[];   // all parsed topics
  scheduledTasks: string[];  // array of Task IDs that were auto-generated by this plan
  isActive: boolean;         // only one plan active at a time
  subjectPriority?: string[]; // user defined priority of subjects
}
